---
- hosts: all
  tasks:
  - name: Install MySQL
    apt: pkg=mysql-server-5.6 state=latest update_cache=yes

  - name: Install MySQL python config library
    apt: pkg=python-mysqldb

  - name: Install a database
    mysql_db: name={{searchfda.mysql.db}} state=present

  - name: Configure MySQL User
    mysql_user: name={{searchfda.mysql.username}} password={{mysql.password}} priv=*.*:ALL state=present

  - name: Add webupd8 repo so we can install Oracle java
    apt_repository: repo='ppa:webupd8team/java'

  - name: Set up Oracle Java debconf answers before running the installer
    debconf: name=oracle-java{{oracle.java.version}}-installer question='shared/accepted-oracle-license-v1-1' vtype='boolean' value=true

  - name: Install Java
    apt: pkg=oracle-java{{oracle.java.version}}-installer state=latest update_cache=yes

  - name: Install Tomcat 7
    apt: pkg=tomcat7 state=latest update_cache=yes

  - name: Install unzip
    apt: pkg=unzip state=latest update_cache=yes

  - name: Install mysql library zip into tmp directory
    get_url: url=http://dev.mysql.com/get/Downloads/Connector-J/{{mysql.connector.package.withversion}}.zip dest=/tmp/mysql-connector-java-5.1.22.zip sha256sum={{mysql.connector.package.sha256sum}}

  - name: Unzip mysql libray and install the library into Tomcat lib directory
    shell: >
        cd /tmp &&
        unzip {{mysql.connector.package.withversion}}.zip &&
        rm {{mysql.connector.package.withversion}}.zip &&
        cp {{mysql.connector.package.withversion}}/{{mysql.connector.package.withversion}}-bin.jar /usr/share/tomcat7/lib &&
        chown root:tomcat7 /usr/share/tomcat7/lib/{{mysql.connector.package.withversion}}-bin.jar &&
        chmod 0644 /usr/share/tomcat7/{{mysql.connector.package.withversion}}-bin.jar &&
        rm -rf /tmp/{{mysql.connector.package.withversion}}

#  - name: Create a WAR file which can be copied to the server.
#    local_action: grails war target/ROOT.war

  - name: Stop Tomcat
    service: name=tomcat7 state=stopped

  - name: Remove old Tomcat ROOT directory
    file: path=/var/lib/tomcat7/webapps/ROOT state=absent

  - name: Copy war file into Tomcat directory
    copy: src=../target/{{webapp.filename}} dest=/var/lib/tomcat7/webapps/{{webapp.filename}} owner=tomcat7 group=tomcat7 mode=644

  - name: Configure Tomcat JVM settings
    copy: src=tomcat7 dest=/etc/default/tomcat7 owner=root group=root mode=644

  - name: Configure app
    copy: src=ServerConfig.groovy.j2 dest=/var/lib/tomcat7/webapps/ServerConfig.groovy.j2 owner=tomcat7 group=tomcat7 mode=644

  - name: restart Tomcat
    service: name=tomcat7 state=started


